import {
  type LucideIcon,
  Database,
  Filter,
  Sigma,
  GitMerge,
  FunctionSquare,
  Table,
  Bot,
  Sparkles,
  Upload,
  Download,
  ToyBrick,
  MousePointer2,
  Trash2,
  FileJson,
  X,
  GripVertical,
  Calculator,
  Minus,
  FileText,
  BrainCircuit,
  Lightbulb,
  Cpu,
  Layers3,
  Zap,
  AreaChart,
  LineChart
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: ToyBrick,
  source: Database,
  filter: Filter,
  aggregate: Sigma,
  join: GitMerge,
  transform: FunctionSquare,
  output: Table,
  bot: Bot,
  sparkles: Sparkles,
  upload: Upload,
  download: Download,
  pointer: MousePointer2,
  trash: Trash2,
  json: FileJson,
  x: X,
  grip: GripVertical,
  calculator: Calculator,
  distinct: Minus,
  fileText: FileText,
  brainCircuit: BrainCircuit,
  lightbulb: Lightbulb,
  cpu: Cpu,
  gravity: Layers3,
  conductivity: Zap,
  resistivity: AreaChart,
  ip: LineChart,
};
